extends Node

signal hasMoved(unit, pos)
signal startTurn
signal endTurn
signal currentUnit
signal endRound
signal deletePassives
signal updateGrid
signal currOppFac(affil)
signal ability(abilityNum, state)
signal activelyQueueing(status)
signal abilityIsQueued
signal abilityExecuted(ability)
signal updateUI
signal showUI
signal startAnimate
signal HpUiFinish # Emitted when floating_hp_bar.gd finishes decrementing health bar
signal showRangeTiles(name)
signal endRangeTiles
signal changeButtonState
signal wipeTilePaths
signal updateInitBox
signal addInitBox(initBox)
signal deleteInitObject
signal changeControls
signal adjustZoom
signal moveCamera
signal deleteMe(unit)
signal actedUI
signal updateFloatingHP
signal updateFloatingAP
signal mouseHovering(isHovering)
signal highlightUnit(unit)
signal highlightInit(unit)
signal remakeUnitList
signal addToUnitList(unit)
signal spawnGroup(id)
signal changeMainPortrait(filename)
signal changeReplyPortrait(filename)
signal checkEvents
signal checkObjective
signal midObjective
signal midObjectiveChecked
signal phaseChange
signal finalBattle
signal spawnDrone
signal showReplyPortrait
signal hideReplyPortrait
signal droneFlyIn
signal droneFlyOut
signal playMusic
signal playSFX
signal showInfoBox
signal quickSwap
signal silenceMusic
